<?php


namespace app\blog\entities;


use yii\behaviors\SluggableBehavior;
use yii\db\ActiveRecord;

/**
 * Class Tag
 * @property integer $id
 * @property string $name
 * @property string $slug
 * @package app\blog\entities
 */
class Tag extends ActiveRecord
{
    public static function create(string $tagName):self
    {
        $tag=new static();
        $tag->name=$tagName;
        return $tag;
    }

    public function edit(string $tagName)
    {
        $this->name=$tagName;
    }

    public function getPosts()
    {
        return $this->hasMany(Post::class, ['id' => 'post_id'])
            ->viaTable('post_tags', ['tag_id' =>'id']);
    }
    public static function tableName()
    {
        return '{{%tags}}';
    }

    public function behaviors()
    {
        return [
            ['class' => SluggableBehavior::class,
            'attribute' => 'name',
            ]
        ]; // TODO: Change the autogenerated stub
    }
}