<?php


namespace app\blog\forms;


use yii\base\Model;

class AttachmentsForm extends Model
{
    public function rules()
    {
        return [
            ['file', 'required']
        ]; // TODO: Change the autogenerated stub
    }
}