<?php


namespace app\blog\forms;


use yii\base\Model;

class TagForm extends Model
{
    public $name;

    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'match', 'pattern' => '/^[a-zа-яё\-]+$/i'],
        ]; // TODO: Change the autogenerated stub
    }

}