<?php

namespace app\controllers;

use app\blog\forms\PostForm;
use app\blog\services\PostManageService;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;

class PostController extends Controller
{
    private $service;

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['create', 'update', 'delete'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'create' => ['post', 'get'],
                    'update' => ['post'],
                    'view' => ['get'],
                    'delete' => ['post']
                ],
            ]
        ]; // TODO: Change the autogenerated stub
    }

    public function __construct($id, $module, PostManageService $service, $config = [])
    {
        $this->service=$service;
        parent::__construct($id, $module, $config);
    }

    public function actionCreate()
    {
        $form=new PostForm();
        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
            $this->service->create($form);
            $this->goHome();
        }

        return $this->render('create', ['model' => $form]);
    }

    public function actionUpdate($id)
    {

    }

    public function actionView($id)
    {

    }

    public function actionDelete($id)
    {

    }

}